### ISSUE TITLE
Increase Grades from 8th to 12th

### ISSUE THREAD

**Issue by craigmcampbell** [SMSK-CO/SMSK#37]
This includes all dropdowns as well as grades serviced in program management.

**Comment by thomasnatalie** [comment]
Again, if this is an easy fix and you do not need any more information, you can go ahead and make this change. Thank you!

**Comment by craigmcampbell** [comment]
Looks like this is already done. I must've worked this one in already.

**Comment by thomasnatalie** [comment]
Great, thanks Craig!

Natalie

*Natalie Thomas, MPH, CHES*
*Child and School Oral Health Coordinator*
P 303-692-2529
4300 Cherry Creek Drive South, Denver, CO  80246-1530
natalie.thomas@state.co.us  I  Oral Health Unit
<https://www.colorado.gov/pacific/cdphe/categories/services-and-information/health/prevention-and-wellness/oral-health>

Cavity Free at Three research
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5497886/>
*Colorado Basic Screening Survey (2016-2017) Results
<https://www.colorado.gov/pacific/sites/default/files/PW_OH_BSSReport.pdf>*
