### ISSUE TITLE
Modify Repair Sealant to Dental Chart

### ISSUE THREAD

**Issue by craigmcampbell** [SMSK-CO/SMSK#39]
This will add two new rows to the chart for repairing sealants.

Waiting on a final decision to move this direction.

**Comment by thomasnatalie** [comment]
Hi Craig, 
@mquigley1 and I received some feedback on this and after a discussion we are thinking it would make the most sense to have the "repaired sealant" combined with line "re-sealed" so the line would say: "Re-sealed/Repaired". Our suggestion for the code would be: "RS/REP". This way, the hygienists are not tripped up by the additional line but they can still record the service. If this isn't possible or you have a better idea, we would love to hear it! Thanks, Natalie

**Comment by craigmcampbell** [comment]
That sounds just fine. I don't have a better alternative to suggest. I will make this one of the next items to be done.

**Comment by craigmcampbell** [comment]
To be done:
- [ ] Re-label RS to RS/REP on the two dental chart lines
- [ ] Update the legend to be RS/REP: Re-Sealed/Repaired
- [ ] On legend, make all codes upper case to match

**Comment by thomasnatalie** [comment]
I see the title changed - do you need more info before this can happen? If no, and it's an easy fix, please go ahead and change. Thanks, Craig.

**Comment by craigmcampbell** [comment]
I don't need any more information on this one. I have it moved to my priority list.
