### ISSUE TITLE
Enrolling New Students Automatically defaults to Male

### ISSUE THREAD

**Issue by mquigley1** [SMSK-CO/SMSK#62]
Hi Craig,
I got a call from one of the programs saying they noticed when they enroll a student with the first 4 choices (first name, last name, gender, and DOB), they are able to select "F".  However, once the next screen pops up, the gender automatically is set back to Male.  I believe they can go ahead and correct this issue by reselecting Female (I was able to do this in the test site).  Can you fix the programming so it doesn't default to Male if they've selected female?
Thanks!
Michelle

**Comment by thomasnatalie** [comment]
Hi Craig, 

I wanted to follow up on this. I just got off the phone with someone from the program (Michelle, it was Christlyn). She said she doesn't know how many kids this might have impacted. I can't see individual students - Craig, is there a way we can see if there is an abnormally high amount of male students? If so, is there any way to go back and fix this without doing it for each individual student?
Thanks!

**Comment by craigmcampbell** [comment]
I just took a look through recent additions to the database and this is definitely a problem.  I stopped scrolling down at enrollment dates of 3/21. I saw instances where the issue had been caught and corrected and I saw ones where there were female names marked as male. I'm not sure how far back this issue goes, I have to assume for a long time.

Is there a time today that we can hop on a call and discuss options?

**Comment by thomasnatalie** [comment]
Hi Craig,

I can chat anytime before 11:50 and any time after 1.

nat

*Natalie Thomas, MPH, CHES*
*Child and School Oral Health Coordinator*
P 303-692-2529
4300 Cherry Creek Drive South, Denver, CO  80246-1530
natalie.thomas@state.co.us  I  Oral Health Unit
<https://www.colorado.gov/pacific/cdphe/categories/services-and-information/health/prevention-and-wellness/oral-health>

Cavity Free at Three research
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5497886/>
*Colorado Basic Screening Survey (2016-2017) Results
<https://www.colorado.gov/pacific/sites/default/files/PW_OH_BSSReport.pdf>*

**Comment by mquigley1** [comment]
Hi, 
I'm available the same times today as Natalie.
Michelle


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
