### ISSUE TITLE
Search Engine Function not working

### ISSUE THREAD

**Issue by thomasnatalie** [SMSK-CO/SMSK#7]
Nancy Hunt in Chaffee County is reporting, "trouble with the search engine. I am not able to pull up names. The search engine says students does not exist, even if I can confirm they are in the database."

**Comment by craigmcampbell** [comment]
@thomasnatalie I have tested this and I'm not seeing any issues. Can you ask Nancy for a couple of examples where she is seeing problems?

**Comment by thomasnatalie** [comment]
@craigmcampbell I am going to attach a couple of screenshots Nancy sent along with a couple of comments. Hopefully this is what you are looking for. 

![screenshotnh5](https://user-images.githubusercontent.com/32399263/33567925-fa8fe03c-d8e1-11e7-840c-f4646f064ca4.jpg)
![screenshotnh5](https://user-images.githubusercontent.com/32399263/33567974-1acf8e6a-d8e2-11e7-9afa-ffa84014f7a8.jpg)

The above 2 screenshots show what happens when Nancy searches for a student.

![screenshotnh1](https://user-images.githubusercontent.com/32399263/33580255-b313b800-d909-11e7-80ab-f91b30f6394a.jpg)
![screenshotnh2](https://user-images.githubusercontent.com/32399263/33580261-b578e728-d909-11e7-825d-51cc1b31fe04.jpg)

The above 2 screenshots show when Nancy tries to search for a school.

**Comment by craigmcampbell** [comment]
I just took a look at the code and it currently does not support searching by first and last name at the same time. It works best to either search by first or last. If you'd like, I can add an issue to add support for this and work it into the queue.

On a side note, I noticed that James Johnson exists twice. They are sequential id numbers, which makes me think that the form might have been submitted twice when he was added.

**Comment by thomasnatalie** [comment]
Would adding an issue to add support change the code and make it so programs could search for first and last name at the same time? I'm thinking about students with common first and last names - As the programs get bigger and bigger, it's going to be helpful to give them as much opportunity to narrow their searches as possible. 

Do the charts for James Johnson match? Is there any way to delete one so that we can have a more accurate count of students?

**Comment by craigmcampbell** [comment]
Yes, the new issue would make it so that it will search by both. It's definitely not great that it doesn't currently work that way.

There are no evaluations yet for that student for either record, so I should be able to remove one of them if you want me to.

**Comment by thomasnatalie** [comment]
I'm going to check with Nancy about deleting the duplicate but I think it would be helpful at this point. I will let you know when I have an answer.

**Comment by craigmcampbell** [comment]
#27 Has been created to resolve this issue.
